package com.lokhate.meteo.utils

import android.content.Context
import android.graphics.Color
import android.graphics.drawable.Drawable
import com.lokhate.meteo.R

object ForecastHelper {
    enum class WeatherStatus {
        SUN, PARTLY_CLOUDY, CLOUDY, RAIN, SNOW, THUNDERSTORMS
    }

    private val weatherStatusCodeMap: Map<Int, WeatherStatus> = mapOf(
        0 to WeatherStatus.SUN,
        1 to WeatherStatus.PARTLY_CLOUDY,
        2 to WeatherStatus.PARTLY_CLOUDY,
        3 to WeatherStatus.PARTLY_CLOUDY,
        4 to WeatherStatus.CLOUDY,
        5 to WeatherStatus.CLOUDY,
        6 to WeatherStatus.CLOUDY,
        7 to WeatherStatus.CLOUDY,
        8 to WeatherStatus.CLOUDY,
        9 to WeatherStatus.CLOUDY,
        10 to WeatherStatus.CLOUDY,
        11 to WeatherStatus.CLOUDY,
        12 to WeatherStatus.CLOUDY,
        20 to WeatherStatus.RAIN,
        21 to WeatherStatus.RAIN,
        22 to WeatherStatus.RAIN,
        23 to WeatherStatus.RAIN,
        24 to WeatherStatus.RAIN,
        25 to WeatherStatus.RAIN,
        26 to WeatherStatus.RAIN,
        27 to WeatherStatus.RAIN,
        28 to WeatherStatus.RAIN,
        29 to WeatherStatus.RAIN,
        30 to WeatherStatus.SNOW,
        31 to WeatherStatus.SNOW,
        32 to WeatherStatus.SNOW,
        33 to WeatherStatus.SNOW,
        34 to WeatherStatus.SNOW,
        35 to WeatherStatus.SNOW,
        36 to WeatherStatus.SNOW,
        37 to WeatherStatus.SNOW,
        38 to WeatherStatus.SNOW,
        39 to WeatherStatus.SNOW,
        40 to WeatherStatus.CLOUDY,
        41 to WeatherStatus.CLOUDY,
        42 to WeatherStatus.CLOUDY,
        43 to WeatherStatus.CLOUDY,
        44 to WeatherStatus.CLOUDY,
        45 to WeatherStatus.CLOUDY,
        46 to WeatherStatus.CLOUDY,
        47 to WeatherStatus.CLOUDY,
        48 to WeatherStatus.CLOUDY,
        49 to WeatherStatus.CLOUDY,
        50 to WeatherStatus.RAIN,
        51 to WeatherStatus.RAIN,
        52 to WeatherStatus.RAIN,
        53 to WeatherStatus.RAIN,
        54 to WeatherStatus.RAIN,
        55 to WeatherStatus.RAIN,
        56 to WeatherStatus.RAIN,
        57 to WeatherStatus.RAIN,
        58 to WeatherStatus.RAIN,
        59 to WeatherStatus.RAIN,
        60 to WeatherStatus.RAIN,
        61 to WeatherStatus.RAIN,
        62 to WeatherStatus.RAIN,
        63 to WeatherStatus.RAIN,
        64 to WeatherStatus.RAIN,
        65 to WeatherStatus.RAIN,
        66 to WeatherStatus.RAIN,
        67 to WeatherStatus.RAIN,
        68 to WeatherStatus.RAIN,
        69 to WeatherStatus.RAIN,
        70 to WeatherStatus.SNOW,
        71 to WeatherStatus.SNOW,
        72 to WeatherStatus.SNOW,
        73 to WeatherStatus.SNOW,
        74 to WeatherStatus.SNOW,
        75 to WeatherStatus.SNOW,
        76 to WeatherStatus.SNOW,
        77 to WeatherStatus.SNOW,
        78 to WeatherStatus.SNOW,
        79 to WeatherStatus.SNOW,
        80 to WeatherStatus.RAIN,
        81 to WeatherStatus.RAIN,
        82 to WeatherStatus.RAIN,
        83 to WeatherStatus.RAIN,
        84 to WeatherStatus.RAIN,
        85 to WeatherStatus.SNOW,
        86 to WeatherStatus.SNOW,
        87 to WeatherStatus.SNOW,
        88 to WeatherStatus.SNOW,
        89 to WeatherStatus.SNOW,
        90 to WeatherStatus.THUNDERSTORMS,
        91 to WeatherStatus.THUNDERSTORMS,
        92 to WeatherStatus.THUNDERSTORMS,
        93 to WeatherStatus.THUNDERSTORMS,
        94 to WeatherStatus.THUNDERSTORMS,
        95 to WeatherStatus.THUNDERSTORMS,
        96 to WeatherStatus.THUNDERSTORMS,
        97 to WeatherStatus.THUNDERSTORMS,
        98 to WeatherStatus.THUNDERSTORMS,
        99 to WeatherStatus.THUNDERSTORMS
    )

    private val weatherCodeMap: Map<Int, Int> = mapOf(
        0 to R.string.clear_sky,
        1 to R.string.partly_cloudy,
        2 to R.string.partly_cloudy,
        3 to R.string.partly_cloudy,
        4 to R.string.visibility_reduced,
        5 to R.string.haze,
        6 to R.string.widespread_dust_in_suspension,
        7 to R.string.duststorm_within_sight_but_not_at_the_station,
        8 to R.string.duststorm_at_the_station_during_the_past_hour,
        9 to R.string.duststorm_at_the_station,
        10 to R.string.mist,
        11 to R.string.patches_of_shallow_fog,
        12 to R.string.more_or_less_continuous_shallow_fog,
        13 to R.string.lightning_visible_no_thunder_heard,
        14 to R.string.precipitation_within_sight_but_not_reaching_the_ground,
        15 to R.string.precipitation_within_sight_reaching_the_ground,
        16 to R.string.precipitation_within_sight_no_occurrence_at_station,
        17 to R.string.thunderstorm_but_no_precipitation_at_station,
        18 to R.string.squalls_at_station,
        19 to R.string.funnel_cloud_s,
        20 to R.string.drizzle,
        21 to (R.string.rain),
        22 to (R.string.snow),
        23 to (R.string.rain_and_snow_mixed),
        24 to (R.string.freezing_drizzle_or_freezing_rain),
        25 to (R.string.showers_of_rain),
        26 to (R.string.showers_of_snow),
        27 to (R.string.showers_of_hail),
        28 to (R.string.showers_of_rain_and_snow_mixed),
        29 to (R.string.showers_of_rain_and_hail_mixed),
        30 to (R.string.slight_or_moderate_dust_or_sand_storm),
        31 to (R.string.slight_or_moderate_dust_or_sand_storm),
        32 to (R.string.slight_or_moderate_dust_or_sand_storm),
        33 to (R.string.severe_dust_or_sand_storm),
        34 to (R.string.severe_dust_or_sand_storm),
        35 to (R.string.severe_dust_or_sand_storm),
        36 to (R.string.slight_or_moderate_blowing_snow),
        37 to (R.string.heavy_drifting_snow),
        38 to (R.string.slight_or_moderate_blowing_snow),
        39 to (R.string.heavy_drifting_snow),
        40 to (R.string.fog_in_past_hour_but_not_at_observation),
        41 to (R.string.fog_in_past_hour_at_observation),
        42 to (R.string.fog_in_past_hour_but_not_at_observation),
        43 to (R.string.fog_in_past_hour_at_observation),
        44 to (R.string.fog_or_ice_fog_in_past_hour_but_not_at_observation),
        45 to (R.string.fog_or_ice_fog_in_past_hour_at_observation),
        46 to (R.string.fog_or_ice_fog_in_past_hour_but_not_at_observation),
        47 to (R.string.fog_or_ice_fog_in_past_hour_at_observation),
        48 to (R.string.fog_depositing_rime),
        49 to (R.string.fog_depositing_rime),
        50 to (R.string.drizzle_not_freezing_intermittent_slight),
        51 to (R.string.drizzle_not_freezing_intermittent_slight),
        52 to (R.string.drizzle_not_freezing_intermittent_moderate),
        53 to (R.string.drizzle_not_freezing_intermittent_moderate),
        54 to (R.string.drizzle_not_freezing_intermittent_heavy),
        55 to (R.string.drizzle_not_freezing_intermittent_heavy),
        56 to (R.string.freezing_drizzle_slight),
        57 to (R.string.freezing_drizzle_moderate),
        58 to (R.string.freezing_drizzle_heavy),
        59 to (R.string.freezing_drizzle_heavy),
        60 to (R.string.rain_intermittent_slight),
        61 to (R.string.rain_continuous_slight),
        62 to (R.string.rain_intermittent_moderate),
        63 to (R.string.rain_continuous_moderate),
        64 to (R.string.rain_intermittent_heavy),
        65 to (R.string.rain_continuous_heavy),
        66 to (R.string.freezing_rain_slight),
        67 to (R.string.freezing_rain_moderate),
        68 to (R.string.freezing_rain_heavy),
        69 to (R.string.freezing_rain_heavy),
        70 to (R.string.intermittent_fall_of_snowflakes_slight),
        71 to (R.string.continuous_fall_of_snowflakes_slight),
        72 to (R.string.intermittent_fall_of_snowflakes_moderate),
        73 to (R.string.continuous_fall_of_snowflakes_moderate),
        74 to (R.string.intermittent_fall_of_snowflakes_heavy),
        75 to (R.string.continuous_fall_of_snowflakes_heavy),
        76 to (R.string.diamond_dust_with_or_without_fog),
        77 to (R.string.snow_grains_with_or_without_fog),
        78 to (R.string.isolated_star_like_snow_crystals),
        79 to (R.string.ice_pellets),
        80 to (R.string.rain_showers_slight),
        81 to (R.string.rain_showers_moderate_or_heavy),
        82 to (R.string.rain_showers_violent),
        83 to (R.string.showers_of_rain_and_snow_mixed_slight),
        84 to (R.string.showers_of_rain_and_snow_mixed_moderate_or_heavy),
        85 to (R.string.snow_showers_slight),
        86 to (R.string.snow_showers_moderate_or_heavy),
        87 to (R.string.snow_showers_heavy),
        88 to (R.string.showers_of_snow_pellets_or_small_hail),
        89 to (R.string.showers_of_snow_pellets_or_small_hail_with_rain_or_snow),
        90 to (R.string.thunderstorm_without_precipitation),
        91 to (R.string.thunderstorm_with_slight_rain),
        92 to (R.string.thunderstorm_with_moderate_or_heavy_rain),
        93 to (R.string.thunderstorm_with_slight_snow),
        94 to (R.string.thunderstorm_with_moderate_or_heavy_snow),
        95 to (R.string.thunderstorm_slight_or_moderate),
        96 to (R.string.thunderstorm_slight_or_moderate_with_hail),
        97 to (R.string.thunderstorm_heavy),
        98 to (R.string.thunderstorm_heavy_with_hail),
        99 to (R.string.tornado)
    )

    fun getWeatherFromCode(context: Context, code: Int): String {
        val stringId = weatherCodeMap[code]
        return if (stringId != null) context.getString(stringId) else "Unknown weather code ($code)"
    }

    private fun getWeatherStatus(code: Int): WeatherStatus {
        return weatherStatusCodeMap[code] ?: WeatherStatus.PARTLY_CLOUDY
    }

    fun getWeatherImage(code: Int): Int {
        return when (getWeatherStatus(code)) {
            WeatherStatus.SUN -> R.drawable.sun
            WeatherStatus.PARTLY_CLOUDY -> R.drawable.partly_cloudy
            WeatherStatus.CLOUDY -> R.drawable.cloudy
            WeatherStatus.RAIN -> R.drawable.rain
            WeatherStatus.SNOW -> R.drawable.snow
            WeatherStatus.THUNDERSTORMS -> R.drawable.thunderstorm
            else -> R.drawable.partly_cloudy
        }
    }
}